- name: Install php-fpm & php extensions
  become: true
  yum: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml

- name: Configure php-fom with apache
  become: true
  copy: src=files/www.conf dest=/etc/php/7.0/fpm/pool.d/

- name: Restart php-fpm
  become: yes
  service: name=php-fpm state=restarted
