- name: Install apache web server
  become: true
  yum: pkg={{ item }} state=installed update_cache=true
  with_items:
  - httpd

- name: Upload apache default configuration
  become: yes
  copy: src=files/000-default.conf dest=/etc/httpd/conf.d/

- name: Upload default index.php for host 
  become: yes
  copy: src=files/index.php dest=/var/www/html/ mode=0644  

- name: Restart webserver
  become: yes
  service: name=httpd state=restarted
